config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User"
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :description, presence: true, length: { minimum: 25 }
  validates :code, presence: true, uniqueness: true, length: { minimum: 20 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :title, presence: true, length: { minimum: 3 }
  validates :looking_for, presence: true, length: { minimum: 10 }
  validates :description, presence: true, length: { minimum: 25 }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat

  validates :content, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chats, class_name: "Chat", foreign_key: "seller_id"
  has_many :chats, class_name: "Chat", foreign_key: "buyer_id"

  has_many :exchanges
  has_many :items
  has_many :messages

  validates :address, presence: true, length: { minimum: 10 }
  validates :first_name, :last_name, :country, :city, :zip_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :first_name, :last_name, :country, :city, :address, :zip_code)}

       devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :first_name, :last_name, :country, :city, :address, :zip_code)}
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_item, only: [:show, :edit, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to items_page
    else
      p @item.errors
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :looking_for, :user_id, :category_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @items = Item.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/format_text_for_cards_helper.rb
module FormatTextForCardsHelper
  def format_text(text)
    if text.length > 240
      text[240..-1] = "..."
      text
    else
      text
    end
  end
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<div class="items-index-container">
  <div class="header">
    <p><%= @items.count %> results</p>
    <h2><%= params[:category] %></h2>
  </div>
  <div class="filters">
    <button>Filter search</button>
  </div>
  <div class="results">
    <%= render 'shared/big_card' %>
  </div>
</div>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' if !(request.original_url.include? "users") %>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' if !(request.original_url.include? "users") %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing-container">
  <div class="categories">
    <h2>Categories</h2>
    <div class="buttons">
      <%= link_to items_path(category: "Books") do %>
        <div class="category">
            <i class="fas fa-book"></i>
            <p>Books</p>
        </div>
      <% end %>
      <%= link_to items_path(category: "Technology") do %>
        <div class="category">
            <i class="fas fa-laptop"></i>
            <p>Tech</p>
        </div>
      <% end %>
      <%= link_to items_path(category: "Clothing") do %>
        <div class="category">
            <i class="fas fa-tshirt"></i>
            <p>Clothing</p>
        </div>
      <% end %>
      <%= link_to items_path(category: "Furniture") do %>
        <div class="category">
            <i class="fas fa-couch"></i>
            <p>Furniture</p>
        </div>
      <% end %>
      <%= link_to items_path(category: "Tools") do %>
        <div class="category">
            <i class="fas fa-tools"></i>
            <p>Tools</p>
        </div>
      <% end %>
      <%= link_to items_path(category: "Toys") do %>
        <div class="category">
            <i class="fas fa-robot"></i>
            <p>Toys</p>
        </div>
      <% end %>
      <%= link_to items_path(category: "Others") do %>
        <div class="category">
            <i class="fas fa-question"></i>
            <p>Others</p>
        </div>
      <% end %>
    </div>
  </div>
  <div class="featured">
    <h2>Featured items</h2>
    <div class="items">
      <%= render 'shared/card' %>
    </div>
  </div>
</div>

app/views/shared/_big_card.html.erb
<% @items.each do |item| %>
  <%= link_to item_path(item) do %>
    <div class="big-card">
      <div class="picture">
      </div>
      <div class="left">
        <div class="details">
          <h4><%= item.title %></h4>
          <p>Looking for: <%= format_text(item.looking_for) %></p>
        </div>
        <div class="date">
          <p><%= item.created_at %></p>
        </div>
      </div>
      <div class="right">
        <div class="user">
          <div class="profile-picture">
          </div>
        </div>
        <div class="heart">
          <i class="far fa-heart" id="card-heart"></i>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_card.html.erb
<% @items.each do |item| %>
  <%= link_to item_path(item) do %>
    <div class="card">
      <div class="picture">

      </div>
      <div class="info">
        <div class="left">
          <h4><%= item.title %></h4>
          <p><%= item.user.city %></p>
        </div>
        <div class="right">
          <i class="far fa-heart" id="card-heart"></i>
        </div>
      </div>
  </div>
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="top">
    <div class="logo">
      <%= link_to root_path do %>
        <%= image_tag "tyche-logo-white.png" %>
      <% end %>

    </div>
    <div class="links">
      <%= link_to "Upload Item", "#" %>
      <%= link_to "About", "#" %>
      <%= link_to "Signup", "#" %>
      <%= link_to "Login", "#" %>
      <%= link_to "Exchanges", "#" %>
    </div>
  </div>
  <div class="bottom">
    <div class="social-media">
      <a href="#">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="#">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="#">
        <i class="fab fa-facebook-f"></i>
      </a>
    </div>
    <div class="brand">
      <p>©Tyche Est.2020</p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="brand">
    <%= link_to root_path do %>
      <%= image_tag "tyche-logo.png" %>
    <% end %>
  </div>
  <div class="search">
    <%= form_tag items_path, method: :get do %>
      <%= text_field_tag :query, params[:query], placeholder: "Search for items"%>
    <% end %>
  </div>
  <div class="links">
    <%= link_to "Upload Item", new_item_path, id: "upload-btn" %>
    <%= link_to "About", "#", id: "chats-btn" %>
    <% if user_signed_in? %>
      <i class="fas fa-user" id="user-btn"></i>
    <% else %>
      <%= link_to "Login", new_user_session_path, id: "chats-btn" %>
    <% end %>
  </div>
  <div class="burguer-menu">
    <div class="lines"></div>
  </div>
</div>

<div class="navbar-dropdown" hidden>
  <%= link_to "#" do %>
    <div class="link">
      <p>Exchanges</p>
    </div>
  <% end %>
  <%= link_to "#" do %>
    <div class="link">
      <p>Profile</p>
    </div>
  <% end %>
  <%= link_to destroy_user_session_path, method: :delete do %>
    <div class="link">
      <p>Logout</p>
    </div>
  <% end %>
</div>

<div class="navbar-dropdown-mobile opacity" hidden>
  <div class="links">
    <% if user_signed_in? %>
      <%= link_to "#" do %>
        <div class="link">
          <p>Upload Item</p>
        </div>
      <% end %>
      <%= link_to "#" do %>
        <div class="link">
          <p>Chats</p>
        </div>
      <% end %>
      <%= link_to "#" do %>
        <div class="link">
          <p>Exchanges</p>
        </div>
      <% end %>
      <%= link_to "#" do %>
        <div class="link">
          <p>Profile</p>
        </div>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete do %>
        <div class="link">
          <p>Logout</p>
        </div>
      <% end %>
    <% else %>
      <%= link_to "#" do %>
        <div class="link">
          <p>Upload Item</p>
        </div>
      <% end %>
      <%= link_to new_user_session_path do %>
        <div class="link">
          <p>Login</p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>